GET http://localhost:8082/database/games/4

###
POST http://localhost:8082/database/games/
content-type: application/json

{
    "id": "4",
    "gameName": "sample",
    "numberOfPlayers": 2
}

###
PUT http://localhost:8082/database/games/4
content-type: application/json

{
    "gameName": "updatedSample",
    "numberOfPlayers": 3
}

###
DELETE http://localhost:8082/database/games/1