name: CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 9
        uses: actions/setup-node@v3
        with:
          java-version: 9

      - name: Build with Maven
        run: mvn clean install
