name: Game History Service
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build Game History Service
      run: mvn -B package --file backend/GameHistoryService/pom.xml
    - name: Test Game History Service
      run: mvn test --file backend/GameHistoryService/pom.xml