name: CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up  AdoptOpenJDK 9
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 9
          maven-version: '3.8.1'

      - name: Maven Version Check
        run: mvn --version

      - name: Install Maven
        run: |
          sudo apt-get install -y maven  # Install Maven

      - name: Clean
        run: |
          mvn clean
      
      - name: Package
        run: |
          mvn package
