name: CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up  AdoptOpenJDK 9
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 9

      - name: Build clean and Create Package
        run: |
          mvn clean package
