name: CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up  AdoptOpenJDK 9
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 9

      - name: Clean
        run: |
          mvn clean package
      
      - name: Package
        run: |
          mvn package
